// swift-tools-version: 6.1

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WakeProtocol",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "WakeProtocol",
            targets: ["AppModule"],
            bundleIdentifier: "com.student.wakeprotocol",
            displayVersion: "1.0",
            bundleVersion: "1",
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources",
            sources: ["App", "Models", "Utilities", "Views"],
            resources: [.process("Resources/Assets.xcassets")],
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)